name: Publish

# Run every Sunday @ 03:00 UTC => 20:00 PST
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * 0'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    # Get the code
    - uses: actions/checkout@v2
      with:
        ref: main
        submodules: true

    # Install dependencies
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.4'
    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.80.0'
    - name: Install libaom
      run: sudo apt-get install libaom-dev
    - name: Install go-html-asset-manager
      run: |
        go install github.com/gauntface/go-html-asset-manager/cmds/v2/htmlassets@latest
        go install github.com/gauntface/go-html-asset-manager/cmds/v2/genimgs@latest
    - name: Install NPM Deps
      run: npm install

    # Build it
    - name: Gen Images
      run: genimgs
    - name: Build
      run: npm run build

    # Deploy to AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    - name: Publish to AWS
      run: npx --package @gauntface/cli gauntface aws s3 deploy-static-site --directory="./public/" --bucket_name="www.gaunt.dev"
      shell: bash